/**
 * MIMOSA - API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@bitapp.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestionTypeEnum } from './questionTypeEnum';
import { AnswerOptionRequest } from './answerOptionRequest';


export interface QuestionRequest { 
    text: string;
    question_type: QuestionTypeEnum;
    answer_options?: Array<AnswerOptionRequest>;
}



